# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "I'm Steve Mould"
tagline: "I make <a href='https://www.youtube.com/stevemould'>YouTube videos</a>, <a href='https://festivalofthespokennerd.com/'>stage shows</a>, TV shows and <a href='https://amzn.to/2D8NjyL'>books</a> about science."
picture: square-face.jpg #keep a 100x100 image inside images folder.
email: steve@stevemould.com
description: > # this means to ignore newlines until "baseurl:"
  Science person on YouTube, TV and Stage. Author of science books
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://steventhebrave.github.io" # the base hostname & protocol for your site
brand-color: '#a1ad59'
brand-second-color: '#5d536b'
permalink: ':title/'

# Footer
credits: webjeda #credits on the footer
# version: 1.0

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

sass:
 style: compressed
  
# disqus-shortname: webjeda-sample
# analytics: UA-83979019-1

include: [_pages]



#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
# prose:
#   rooturl: ''
#   siteurl: 'http://prose.github.io/starter/'
#   relativeLinks: 'http://prose.github.io/starter/links.jsonp'
#   media: 'images'
#   ignore:
#     - index.md
#     - _config.yml
#     - /_layouts
#     - /_includes


# gems: [jekyll-paginate, jekyll-seo-tag]
plugins:
  - jekyll-seo-tag